services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.dev
    container_name: classificaedu_app_dev
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env.docker.dev
    depends_on:
      - postgres
      - redis
      - mailhog

  postgres:
    image: postgres:16-alpine
    container_name: classificaedu_postgres_dev
    environment:
      POSTGRES_DB: classificaedu
      POSTGRES_USER: classificaedu
      POSTGRES_PASSWORD: classificaedu
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data/postgres-dev:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: classificaedu_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - ./docker/data/redis-dev:/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: classificaedu_mailhog_dev
    ports:
      - "1025:1025"
      - "8025:8025"

